// Plantilla de inventario que parte igual en todas las propiedades.
export const DEFAULT_INVENTORY_TEMPLATE: Array<{
  category: string;
  name: string;
  quantity: number;
}> = [
  // Cocina
  { category: "Cocina", name: "Licuadora", quantity: 1 },
  { category: "Cocina", name: "Airfryer", quantity: 1 },
  { category: "Cocina", name: "Cafetera", quantity: 1 },
  { category: "Cocina", name: "Microondas", quantity: 1 },
  { category: "Cocina", name: "Horno tostador", quantity: 1 },
  { category: "Cocina", name: "Sandwichera", quantity: 0 },
  { category: "Cocina", name: "Vasos vidrio", quantity: 4 },
  { category: "Cocina", name: "Copas de vino", quantity: 2 },
  { category: "Cocina", name: "Pocillos", quantity: 4 },
  { category: "Cocina", name: "Platos medianos", quantity: 4 },
  { category: "Cocina", name: "Platos grandes", quantity: 4 },
  { category: "Cocina", name: "Platos hondos", quantity: 4 },
  { category: "Cocina", name: "Cocas plásticas", quantity: 4 },
  { category: "Cocina", name: "Cucharas grandes", quantity: 4 },
  { category: "Cocina", name: "Cucharas pequeñas", quantity: 4 },
  { category: "Cocina", name: "Tenedor", quantity: 4 },
  { category: "Cocina", name: "Cuchillos", quantity: 4 },
  { category: "Cocina", name: "Cuchillos grandes", quantity: 1 },
  { category: "Cocina", name: "Abrelatas", quantity: 1 },
  { category: "Cocina", name: "Sacacorchos", quantity: 1 },
  { category: "Cocina", name: "Afilador", quantity: 1 },
  { category: "Cocina", name: "Rallador", quantity: 1 },
  { category: "Cocina", name: "Tabla de picar", quantity: 1 },
  { category: "Cocina", name: "Exprimidor", quantity: 1 },
  { category: "Cocina", name: "Tijeras", quantity: 1 },
  { category: "Cocina", name: "Cucharones (utensilio)", quantity: 4 },
  { category: "Cocina", name: "Trapos cocina", quantity: 1 },
  { category: "Cocina", name: "Nevera", quantity: 1 },

  // General
  { category: "General", name: "Ventilador", quantity: 1 },
  { category: "General", name: "Cama", quantity: 1 },
  { category: "General", name: "TV", quantity: 1 },
  { category: "General", name: "Sofá", quantity: 1 },
  { category: "General", name: "Sillas barra", quantity: 2 },
  { category: "General", name: "Tapete de baño", quantity: 1 },
  { category: "General", name: "Jabonera baño", quantity: 1 },
  { category: "General", name: "Secador de pelo", quantity: 1 },
  { category: "General", name: "Plancha", quantity: 1 },
  { category: "General", name: "Tendedero de ropa", quantity: 1 },
  { category: "General", name: "Mesa de planchar", quantity: 1 },
  { category: "General", name: "Aire acondicionado", quantity: 1 },
  { category: "General", name: "Chapa digital", quantity: 1 },
  { category: "General", name: "Control aire acondicionado", quantity: 1 },
  { category: "General", name: "Control TV", quantity: 1 },
  { category: "General", name: "Toallas grandes", quantity: 4 },
  { category: "General", name: "Toallas pequeñas", quantity: 2 },
];
